#!/bin/sh

# 解决部分软件图形界面打开缓慢问题
exec dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

# 认证弹框
/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 > /dev/null &

#---------------------------环境变量
# 默认输入法框架
export XMODIFIERS="@im=fcitx"

# dwm相关脚本路径
export SDE_SCRIPTS=~/sde/scripts
export DWM_SCRIPTS=~/sde/scripts/dwm
export DWM_BK_SCRIPTS=~/sde/scripts/dwm/blocks


#---------------------------启动程序
# 输入法
fcitx5 &

# 通知中心
dunst &

# 显示设置
bash ~/sde/scripts/display/display_init.sh

# 壁纸
bash ~/sde/scripts/switch_wallpapers.sh

# 混成器（动画）
picom &

# 状态栏
dwmblocks &

# 默认键盘配置
bash ~/sde/scripts/keyboard/default_keyboard_opts.sh

#---------------------------启动dwm
# 启动dwm
# exec dwm > ~/space/tmp/dwm_log.txt 2>&1
exec dwm
